### ISSUE TITLE
Exception occurred: getaddrinfo() takes no keyword arguments

### ISSUE THREAD

**Issue by attila-kocsis** [hjacobs/local-cname#1]
I installed local-cname on a new Ubuntu 18.04 VM. First I installed Python on it with "sudo apt-get install python-pip" and then local-cname with "sudo pip install -U local-cname". When I tried "sudo local-cname google.com duckduckgo.com" I received the following: "ImportError: No module named pathlib". I then installed pathlib with "sudo pip install pathlib".
Now when I try "sudo local-cname google.com duckduckgo.com" I receive this: "Resolving duckduckgo.com .. EXCEPTION OCCURRED: getaddrinfo() takes no keyword arguments". Please see the screenshot attached.
![local_cname_issue](https://user-images.githubusercontent.com/15924774/51197228-31035e00-18f1-11e9-9af5-9fe19935e299.png)

**Comment by eddi-exp** [comment]
macOS
Python 2.7.16

`Traceback (most recent call last):
  File "/usr/local/bin/local-cname", line 11, in <module>
    load_entry_point('local-cname==0.3', 'console_scripts', 'local-cname')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/local_cname/cli.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib`

**Comment by dfrieling** [comment]
came across the same problem - installed local-cname via pip3, ran it via python3 -> works
